<a href="https://colab.research.google.com/github/Dolczi/PytorchTutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR MATH OPERATIONS**

* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and Longhand
* Reassingnment

In [2]:
import torch

In [22]:
tensor_a = torch.tensor(([1,2,3,4]))
tensor_b = torch.tensor(([5,6,7,8]))

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [7]:
# Subtraction Longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Multiplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [15]:
# Exponens / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [16]:
# Exponens Longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [24]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
# Reasignment
tensor_a.add_(tensor_b) # tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])