<a href="https://colab.research.google.com/github/Dolczi/PytorchTutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**


* A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
* Similar to Numpy.Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
* Default datat type of float32.
* More suitable for deep learning than numpy arrays.



In [1]:
import torch
import numpy as np

# **LISTS**

In [2]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.45054903, 0.00989448, 0.33430016, 0.11716545],
       [0.13833047, 0.66546925, 0.29016239, 0.44208058],
       [0.52706643, 0.6272253 , 0.85483381, 0.24863901]])

In [6]:
np1.dtype

dtype('float64')

# **TENSORS**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.7535,  0.3114,  0.8240,  1.5037],
        [-0.5795,  1.3433, -1.4162, -0.7177],
        [-1.4123, -0.9420,  0.3225,  0.2687]])

In [8]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4505, 0.0099, 0.3343, 0.1172],
        [0.1383, 0.6655, 0.2902, 0.4421],
        [0.5271, 0.6272, 0.8548, 0.2486]], dtype=torch.float64)